# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.holidays_service:
      class:     AppBundle\Service\FrenchHolidaysStringDateGenerator
      arguments: 
        []
    app.bill_service:
        class: AppBundle\Service\BillService
        arguments:
            - '@form.factory'
            - '@request_stack'
            - '@app.bill_session_service'
            - '@app.ticket_service'
    app.ticket_service:
        class: AppBundle\Service\TicketService
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
    app.bill_session_service:
        class: AppBundle\Service\BillSessionService
        arguments:
            - '@request_stack'
    app.page_service:
        class: AppBundle\Service\PageService
        arguments:
            - '@request_stack'
            - '@twig'
            - '@app.redirect_service'
            - '@app.bill_service'
            - '@app.bill_session_service'
            - '@app.ticket_service'
            - '@app.holidays_service'
            - '@app.stripe_service'
            - '@app.email_service'
            - '@app.bill_manager'
    app.stripe_service:
        class: AppBundle\Service\StripeService
        arguments:
            - '%app.stripe%'
    app.email_service:
        class: AppBundle\Service\EmailService
        arguments:
            - '%app.email%'
            - '@twig'
    app.date_of_booking_validator:
        class: AppBundle\Validator\Constraints\ValidDateOfBookingValidator
        tags:
            - { name: validator.constraint_validator }
        arguments:
            - '@app.holidays_service'
    app.reduced_price_validator:
        class: AppBundle\Validator\Constraints\ValidReducedPriceValidator
        tags:
            - { name: validator.constraint_validator }
        arguments:
            - '@app.ticket_service'
    app.redirect_service:
        class: AppBundle\Service\RedirectService
        arguments:
            - '@router'
    app.exception_listener:
        class: AppBundle\Listener\BillNotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments:
            - '@app.redirect_service'
    app.bill_manager:
        class: AppBundle\Manager\BillManager
        arguments:
            - '@doctrine.orm.default_entity_manager'