# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.holidays_service:
      class:     AppBundle\Service\FrenchHolidaysStringDateGenerator
      arguments: 
        []
    app.bill_service:
        class: AppBundle\Service\BillService
        arguments:
            - '@form.factory'
            - '@request_stack'
            - '@app.bill_session_service'
            - '@app.ticket_service'
    app.ticket_service:
        class: AppBundle\Service\TicketService
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
            - '@app.ticket_session_service'
    app.bill_session_service:
        class: AppBundle\Service\BillSessionService
        arguments:
            - '@request_stack'
    app.ticket_session_service:
        class: AppBundle\Service\TicketSessionService
        arguments:
            - '@request_stack'
    app.page_service:
        class: AppBundle\Service\PageService
        arguments:
            - '@request_stack'
            - '@app.bill_service'
            - '@twig'
            - '@app.holidays_service'
    app.date_of_booking_validator:
        class: AppBundle\Validator\Constraints\ValidDateOfBookingValidator
        tags:
            - { name: validator.constraint_validator }
        arguments:
            - '@app.holidays_service'