# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.holidays:
      class:     AppBundle\Service\FrenchHolidaysStringDateGenerator
      arguments: 
        []
    app.bill_manager:
        class: AppBundle\Manager\BillManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@form.factory'
            - '@request_stack'
