<?php
namespace AppBundle\Form;

use AppBundle\Entity\Ticket;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class TicketStep2Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, array('attr' => array('placeholder' => 'firstnamePlaceHolder')))
            ->add('lastname', TextType::class, array('attr' => array('placeholder' => 'lastnamePlaceHolder')))
            ->add('date_of_birth', TextType::class, array('attr' => array('placeholder' => 'dateOfBirthPlaceHolder')))
            ->add('country_code', CountryType::class, array('data' => 'FR'))
          /*
            ->add('country_code', ChoiceType::class, array(
                'choices' => array(
                    "Afghanistan " => "AF",
                    "Albania " => "AL",
                    "Algeria " => "DZ",
                    "American Samoa" => "AS",
                    "Andorra, Principality of " => "AD",
                    "Angola" => "AO",
                    "Anguilla " => "AI",
                    "Antarctica" => "AQ",
                    "Antigua and Barbuda" => "AG",
                    "Argentina " => "AR",
                    "Armenia" => "AM",
                    "Aruba" => "AW",
                    "Australia" => "AU",
                    "Austria" => "AT",
                    "Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)" => "AZ",
                    "Bahamas, Commonwealth of The" => "BS",
                    "Bahrain, Kingdom of (Former Dilmun)" => "BH",
                    "Bangladesh (Former East Pakistan)" => "BD",
                    "Barbados " => "BB",
                    "Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)" => "BY",
                    "Belgium " => "BE",
                    "Belize (Former British Honduras)" => "BZ",
                    "Benin (Former Dahomey)" => "BJ",
                    "Bermuda " => "BM",
                    "Bhutan, Kingdom of" => "BT",
                    "Bolivia " => "BO",
                    "Bosnia and Herzegovina " => "BA",
                    "Botswana (Former Bechuanaland)" => "BW",
                    "Bouvet Island (Territory of Norway)" => "BV",
                    "Brazil " => "BR",
                    "British Indian Ocean Territory (BIOT)" => "IO",
                    "Brunei (Negara Brunei Darussalam) " => "BN",
                    "Bulgaria " => "BG",
                    "Burkina Faso (Former Upper Volta)" => "BF",
                    "Burundi (Former Urundi)" => "BI",
                    "Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)" => "KH",
                    "Cameroon (Former French Cameroon)" => "CM",
                    "Canada " => "CA",
                    "Cape Verde " => "CV",
                    "Cayman Islands " => "KY",
                    "Central African Republic " => "CF",
                    "Chad " => "TD",
                    "Chile " => "CL",
                    "China " => "CN",
                    "Christmas Island " => "CX",
                    "Cocos (Keeling) Islands " => "CC",
                    "Colombia " => "CO",
                    "Comoros, Union of the " => "KM",
                    "Congo, Democratic Republic of the (Former Zaire) " => "CD",
                    "Congo, Republic of the" => "CG",
                    "Cook Islands (Former Harvey Islands)" => "CK",
                    "Costa Rica " => "CR",
                    "Cote D'Ivoire (Former Ivory Coast) " => "CI",
                    "Croatia (Hrvatska) " => "HR",
                    "Cuba " => "CU",
                    "Cyprus " => "CY",
                    "Czech Republic" => "CZ",
                    "Czechoslavakia (Former) See CZ Czech Republic or Slovakia" => "CS",
                    "Denmark " => "DK",
                    "Djibouti (Former French Territory of the Afars and Issas, French Somaliland)" => "DJ",
                    "Dominica " => "DM",
                    "Dominican Republic " => "DO",
                    "East Timor (Former Portuguese Timor)" => "TP",
                    "Ecuador " => "EC",
                    "Egypt (Former United Arab Republic - with Syria)" => "EG",
                    "El Salvador " => "SV",
                    "Equatorial Guinea (Former Spanish Guinea)" => "GQ",
                    "Eritrea (Former Eritrea Autonomous Region in Ethiopia)" => "ER",
                    "Estonia (Former Estonian Soviet Socialist Republic)" => "EE",
                    "Ethiopia (Former Abyssinia, Italian East Africa)" => "ET",
                    "Falkland Islands (Islas Malvinas) " => "FK",
                    "Faroe Islands " => "FO",
                    "Fiji " => "FJ",
                    "Finland " => "FI",
                    "France " => "FR",
                    "French Guiana or French Guyana " => "GF",
                    "French Polynesia (Former French Colony of Oceania)" => "PF",
                    "French Southern Territories and Antarctic Lands " => "TF",
                    "Gabon (Gabonese Republic)" => "GA",
                    "Gambia, The " => "GM",
                    "Georgia (Former Georgian Soviet Socialist Republic)" => "GE",
                    "Germany " => "DE",
                    "Ghana (Former Gold Coast)" => "GH",
                    "Gibraltar " => "GI",
                    "Great Britain (United Kingdom) " => "GB",
                    "Greece " => "GR",
                    "Greenland " => "GL",
                    "Grenada " => "GD",
                    "Guadeloupe" => "GP",
                    "Guam" => "GU",
                    "Guatemala " => "GT",
                    "Guinea (Former French Guinea)" => "GN",
                    "Guinea-Bissau (Former Portuguese Guinea)" => "GW",
                    "Guyana (Former British Guiana)" => "GY",
                    "Haiti " => "HT",
                    "Heard Island and McDonald Islands (Territory of Australia)" => "HM",
                    "Holy See (Vatican City State)" => "VA",
                    "Honduras " => "HN",
                    "Hong Kong " => "HK",
                    "Hungary " => "HU",
                    "Iceland " => "IS",
                    "India " => "IN",
                    "Indonesia (Former Netherlands East Indies; Dutch East Indies)" => "ID",
                    "Iran, Islamic Republic of" => "IR",
                    "Iraq " => "IQ",
                    "Ireland " => "IE",
                    "Israel " => "IL",
                    "Italy " => "IT",
                    "Jamaica " => "JM",
                    "Japan " => "JP",
                    "Jordan (Former Transjordan)" => "JO",
                    "Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)" => "KZ",
                    "Kenya (Former British East Africa)" => "KE",
                    "Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)" => "KI",
                    "Korea, Democratic People's Republic of (North Korea)" => "KP",
                    "Korea, Republic of (South Korea) " => "KR",
                    "Kuwait " => "KW",
                    "Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)" => "KG",
                    "Lao People's Democratic Republic (Laos)" => "LA",
                    "Latvia (Former Latvian Soviet Socialist Republic)" => "LV",
                    "Lebanon " => "LB",
                    "Lesotho (Former Basutoland)" => "LS",
                    "Liberia " => "LR",
                    "Libya (Libyan Arab Jamahiriya)" => "LY",
                    "Liechtenstein " => "LI",
                    "Lithuania (Former Lithuanian Soviet Socialist Republic)" => "LT",
                    "Luxembourg " => "LU",
                    "Macau " => "MO",
                    "Macedonia, The Former Yugoslav Republic of" => "MK",
                    "Madagascar (Former Malagasy Republic)" => "MG",
                    "Malawi (Former British Central African Protectorate, Nyasaland)" => "MW",
                    "Malaysia " => "MY",
                    "Maldives " => "MV",
                    "Mali (Former French Sudan and Sudanese Republic) " => "ML",
                    "Malta " => "MT",
                    "Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)" => "MH",
                    "Martinique (French) " => "MQ",
                    "Mauritania " => "MR",
                    "Mauritius " => "MU",
                    "Mayotte (Territorial Collectivity of Mayotte)" => "YT",
                    "Mexico " => "MX",
                    "Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)" => "FM",
                    "Moldova, Republic of" => "MD",
                    "Monaco, Principality of" => "MC",
                    "Mongolia (Former Outer Mongolia)" => "MN",
                    "Montserrat " => "MS",
                    "Morocco " => "MA",
                    "Mozambique (Former Portuguese East Africa)" => "MZ",
                    "Myanmar, Union of (Former Burma)" => "MM",
                    "Namibia (Former German Southwest Africa, South-West Africa)" => "NA",
                    "Nauru (Former Pleasant Island)" => "NR",
                    "Nepal " => "NP",
                    "Netherlands " => "NL",
                    "Netherlands Antilles (Former Curacao and Dependencies)" => "AN",
                    "New Caledonia " => "NC",
                    "New Zealand (Aotearoa) " => "NZ",
                    "Nicaragua " => "NI",
                    "Niger " => "NE",
                    "Nigeria " => "NG",
                    "Niue (Former Savage Island)" => "NU",
                    "Norfolk Island " => "NF",
                    "Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)" => "MP",
                    "Norway " => "NO",
                    "Oman, Sultanate of (Former Muscat and Oman)" => "OM",
                    "Pakistan (Former West Pakistan)" => "PK",
                    "Palau (Former Palau District - Trust Terriroty of the Pacific Islands)" => "PW",
                    "Palestinian State (Proposed)" => "PS",
                    "Panama " => "PA",
                    "Papua New Guinea (Former Territory of Papua and New Guinea)" => "PG",
                    "Paraguay " => "PY",
                    "Peru " => "PE",
                    "Philippines " => "PH",
                    "Pitcairn Island" => "PN",
                    "Poland " => "PL",
                    "Portugal " => "PT",
                    "Puerto Rico " => "PR",
                    "Qatar, State of " => "QA",
                    "Reunion (French) (Former Bourbon Island)" => "RE",
                    "Romania " => "RO",
                    "Russia - USSR (Former Russian Empire, Union of Soviet Socialist Republics, Russian Soviet Federative Socialist Republic) Now RU - Russian Federation" => "SU",
                    "Russian Federation " => "RU",
                    "Rwanda (Rwandese Republic) (Former Ruanda)" => "RW",
                    "Saint Helena " => "SH",
                    "Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)" => "KN",
                    "Saint Lucia " => "LC",
                    "Saint Pierre and Miquelon " => "PM",
                    "Saint Vincent and the Grenadines " => "VC",
                    "Samoa (Former Western Samoa)" => "WS",
                    "San Marino " => "SM",
                    "Sao Tome and Principe " => "ST",
                    "Saudi Arabia " => "SA",
                    "Serbia, Republic of" => "RS",
                    "Senegal " => "SN",
                    "Seychelles " => "SC",
                    "Sierra Leone " => "SL",
                    "Singapore " => "SG",
                    "Slovakia" => "SK",
                    "Slovenia " => "SI",
                    "Solomon Islands (Former British Solomon Islands)" => "SB",
                    "Somalia (Former Somali Republic, Somali Democratic Republic) " => "SO",
                    "South Africa (Former Union of South Africa)" => "ZA",
                    "South Georgia and the South Sandwich Islands" => "GS",
                    "Spain " => "ES",
                    "Sri Lanka (Former Serendib, Ceylon) " => "LK",
                    "Sudan (Former Anglo-Egyptian Sudan) " => "SD",
                    "Suriname (Former Netherlands Guiana, Dutch Guiana)" => "SR",
                    "Svalbard (Spitzbergen) and Jan Mayen Islands " => "SJ",
                    "Swaziland, Kingdom of " => "SZ",
                    "Sweden " => "SE",
                    "Switzerland " => "CH",
                    "Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)" => "SY",
                    "Taiwan (Former Formosa)" => "TW",
                    "Tajikistan (Former Tajik Soviet Socialist Republic)" => "TJ",
                    "Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)" => "TZ",
                    "Thailand (Former Siam)" => "TH",
                    "Togo (Former French Togoland)" => "TG",
                    "Tokelau " => "TK",
                    "Tonga, Kingdom of (Former Friendly Islands)" => "TO",
                    "Trinidad and Tobago " => "TT",
                    "Tromelin Island " => "TE",
                    "Tunisia " => "TN",
                    "Turkey " => "TR",
                    "Turkmenistan (Former Turkmen Soviet Socialist Republic)" => "TM",
                    "Turks and Caicos Islands " => "TC",
                    "Tuvalu (Former Ellice Islands)" => "TV",
                    "Uganda, Republic of" => "UG",
                    "Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)" => "UA",
                    "United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)" => "AE",
                    "United Kingdom (Great Britain / UK)" => "GB",
                    "United States " => "US",
                    "United States Minor Outlying Islands " => "UM",
                    "Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)" => "UY",
                    "Uzbekistan (Former UZbek Soviet Socialist Republic)" => "UZ",
                    "Vanuatu (Former New Hebrides)" => "VU",
                    "Vatican City State (Holy See)" => "VA",
                    "Venezuela " => "VE",
                    "Vietnam " => "VN",
                    "Virgin Islands, British " => "VI",
                    "Virgin Islands, United States (Former Danish West Indies) " => "VQ",
                    "Wallis and Futuna Islands " => "WF",
                    "Western Sahara (Former Spanish Sahara)" => "EH",
                    "Yemen " => "YE",
                    "Yugoslavia " => "YU",
                    "Zaire (Former Congo Free State, Belgian Congo, Congo/Leopoldville, Congo/Kinshasa, Zaire) Now CD - Congo, Democratic Republic of the " => "ZR",
                    "Zambia, Republic of (Former Northern Rhodesia) " => "ZM",
                    "Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia) " => "ZW",
                ),
                'data' => 'FR'   
            ))
            */
            ->add('reduced_price', CheckboxType::class, array(
                'label'        => 'Tarif réduit',
                'value'         => true,
                'required'     => false
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Ticket::class,
            'error_mapping' => array(
                '.' => 'country_code',
            )
        ));
    }
}